### ISSUE TITLE
How do you build the images?

### ISSUE THREAD

**Issue by jchromik** [hpi-swa/filetreeCI#4]
Since you are downloading the Squeak images from the HPI server we assume you are not using an image which is also hosted at squeak.org.
How do you build these images and why don't you just use the stock images?

Thank you in advance!

**Comment by fniephaus** [comment]
builderCI and filetreeCI rely on Filtree/Metacello and installing this takes some time.
Since filetreeCI aims to be a lot faster than builderCI, it uses prepared images that have Filetree preinstalled.
You might want to have a look at the [build](https://github.com/hpi-swa/filetreeCI/tree/build) branch which automates the image preparation.
Here is a (probably incomplete) list of things that happen during this preparation:
- Update Squeak image
- Redirect `Transcript` to `stdout`
- Enable image closing on error (so that Travis builds don't hang)
- Install Filetree/Metacello
- Set author credentials

Hope this helps.
